

services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  node:
    build: ./node
    container_name: node
    working_dir: /usr/src/app
    volumes:
      - ./node:/usr/src/app
    tty: true
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - node
